name: Docker Image CI  # Name of the workflow

on:  # Trigger the workflow on push events to the main branch
  push:
    branches: [ "main" ]

env:  # Define environment variables
  LATEST_TAG: mumfford/liatrio-exercise-jackm:latest  # Docker image tag

jobs:  # Define the jobs to be run
  docker:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:  # Define the steps in the job
      - name: Checkout repository 
        uses: actions/checkout@v3  

      - name: Node.js setup 
        uses: actions/setup-node@v3 
        with:
          node-version: '18' 
          
      - name: Install Node.js dependencies  
        run: npm install 

      - name: Set up Docker Buildx  
        uses: docker/setup-buildx-action@v3 
    
      - name: Login to Docker Hub  
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username from secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password from secrets

      - name: Build docker img  
        run: docker buildx build -t ${{ env.LATEST_TAG }} . 

      - name: Run container in background  # needs to be done before tests
        run: |
          docker run --name test_container -d -p 80:80 ${{ env.LATEST_TAG }} 

      - name: Run tests  # Step to run tests
        uses: liatrio/github-actions/apprentice-action@v1.0.0  # Use a custom action to run tests

      - name: Stop and remove container
        run: |
          docker stop test_container  
          docker rm test_container 

      - name: Build and export to Docker LATEST  # Step to build and push the Docker image
        uses: docker/build-push-action@v6  
        with:
          platforms: linux/amd64,linux/arm64  # Specify the platforms
          push: true  
          tags: ${{ env.LATEST_TAG }}  