name: Docker Image CI

on:
  push:

env:
  TEST_TAG: mumfford/liatrio-exercise-jackm:test
  LATEST_TAG: mumfford/liatrio-exercise-jackm:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        run: npm install
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test
        run: |
          docker run -p 80:80 ${{ env.TEST_TAG }}
        
      - name: run tests
        uses: liatrio/github-actions/apprentice-action@master
